<a href="https://colab.research.google.com/github/guanidine/Machine-Learning-Basics/blob/main/01.tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

## Initializing Tensor

In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [4]:
# Other common initialization methods
x = torch.empty(size=(3, 3))
x = torch.zeros((3, 3))
x = torch.rand((3, 3))
x = torch.ones((3, 3))
x = torch.eye(5, 5)  # I
x = torch.arange(start=0, end=5, step=1)
x = torch.linspace(start=0.1, end=1, steps=10)
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [5]:
# How to make initialized tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor.bool())  # boolean True/False
print(tensor.short())  # int16
print(tensor.long())  # int64(Important)
print(tensor.half())  # float16
print(tensor.float())  # float32(Important)
print(tensor.double())  # float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [6]:
# Array to Tensor conversion and vice-versa
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()
print(tensor)
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Tensor Math & Comparison Operations

In [7]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [8]:
# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)
z = x + y
print(z)

tensor([10, 10, 10])


In [9]:
# Subtraction
z = x - y
print(z)

tensor([-8, -6, -4])


In [10]:
# Division
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [11]:
# Inplace operations
t = torch.zeros(3)
t.add_(x)
t += x
print(t)

tensor([2., 4., 6.])


In [12]:
# Exponentiation
z = x.pow(2)
z = x ** 2
print(z)

tensor([1, 4, 9])


In [13]:
# Simple comparison
z = x > 0
z = x < 0

In [14]:
# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
x3 = x1.mm(x2)
print(x3)

tensor([[1.4771, 1.3145, 0.2076],
        [0.7735, 0.8542, 0.1385]])


In [15]:
# Matrix exponentiation
matrix_exp = torch.rand(3, 3)
print(matrix_exp.matrix_power(3))

tensor([[1.1732, 1.8243, 1.1495],
        [1.2881, 2.0736, 1.2094],
        [1.1264, 1.8600, 1.0514]])


In [16]:
# Element wise multi
z = x * y
print(z)

tensor([ 9, 16, 21])


In [17]:
# Dot product
z = torch.dot(x, y)
print(z)

tensor(46)


In [18]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # (b x n x p)
print(tensor1.shape)
print(tensor2.shape)
print(out_bmm.shape)

torch.Size([32, 10, 20])
torch.Size([32, 20, 30])
torch.Size([32, 10, 30])


In [19]:
# Example of broadcasting
x1 = torch.rand((2, 2))
x2 = torch.rand((1, 2))

# Shape of z is 2x2: How? The 1x2 vector (x2) is subtracted for each row in the 2x2 (x1)
z = x1 - x2
print(z)
# Shape of z is 2x2: How? Broadcasting! Element wise exponentiation for every row
z = x1 ** x2
print(z)

tensor([[ 0.4246, -0.4179],
        [ 0.0724,  0.1346]])
tensor([[0.9366, 0.3129],
        [0.7445, 0.8050]])


In [20]:
# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
print(sum_x)
value, indices = torch.max(x, dim=0)  # x.max(dim=0)
print(value, indices)
value, indices = torch.min(x, dim=0)
print(value, indices)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y)
print(z)
sorted_y = torch.sort(y, dim=0, descending=False)
print(sorted_y)
z = torch.clamp(x, min=1 + 1e-3)
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
z = torch.any(x)  # x.any()
print(z)
z = x.all()  # torch.all(x)
print(z)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([False, False, False])
torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))
tensor(True)
tensor(False)


## Tensor Indexing

In [21]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape)  # x[0,:]
print(x[:, 0].shape)
print(x[2, 0:10])  # 0:10 -> [0, 1, 2, ..., 9]

x[0, 0] = 100

torch.Size([25])
torch.Size([10])
tensor([0.4097, 0.9933, 0.5993, 0.1140, 0.6852, 0.4510, 0.5757, 0.0478, 0.6739,
        0.7614])


In [22]:
# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols].shape)

tensor([2, 5, 8])
torch.Size([2])


In [23]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [24]:
# Useful operation
print(torch.where(x > 5, x, x * 2))
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())
print(torch.rand((5, 5, 5)).ndimension())
print(torch.rand((5, 5, 5)).numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
3
125


## Tensor Reshaping

In [25]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)  # stored contiguously
x_3x3 = x.resize(3, 3)  # copy to make it contiguously stored, some performance loss
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


/usr/local/lib/python3.9/dist-packages/torch/_tensor.py:761: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [26]:
y = x_3x3.t()
print(y)
print(y.contiguous().view(9))
print(y.reshape(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [27]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [28]:
z = x1.view(-1)
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([10])
torch.Size([64, 10])


In [29]:
z = x.permute(0, 2, 1)
print(x.shape)
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 5, 2])


In [30]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [31]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

z = x.squeeze(1)
print(z.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
